name = "IEDD Notebook"
prefix = "iedd"
author = "PRION - Team"

[files]
include = [
    "mod.cpp",
    "README*.md",
    "AUTHORS.txt",
    "LICENSE",
]

releasebuild = [
    "@zip iedd_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]
